### PR TITLE
added Jenkinsfile for worker with build job

### PR DESCRIPTION
**Pull request by Leogeo80**
- added Jenkinsfile for worker app
-  Currently it only has a working spec build job, using mock steps for rest of the jobs

### CODE REVIEW

**Review by Leogeo80 — COMMENTED** [review]
canèt approve

**Review by leogeo80itleo — APPROVED** [review]
changes approved

**Review by leogeo80itleo — APPROVED** [review]
changes approved

**Review by leogeo80itleo — APPROVED** [review]
changes and remove README2.md approved

**Pull request merged**
