### PR TITLE
Feature/workerpipe2

### PR DESCRIPTION
**Pull request by Leogeo80**

### CODE REVIEW

**Review by Leogeo80 — COMMENTED** [review]
leogeo80itleo approve please

**Review by leogeo80itleo — APPROVED** [review]
Approve

**Comment by leogeo80itleo** [comment]
No comments

**Review by Leogeo80 — COMMENTED** [review]
kk

**Review by leogeo80itleo — APPROVED** [review]

**Comment by leogeo80itleo** [comment]
ok

**Comment by Leogeo80** [comment]
dfd

**Comment by Leogeo80** [comment]
fdfd

**Review by Leogeo80 — COMMENTED** [review]
fdf

**Review by leogeo80itleo — COMMENTED** [review]
branch deleted

**Comment by leogeo80itleo** [comment]
dsd

**Pull request closed without merging**
